AllCops:
  Include:
    - '**/*.gemspec'
    - '**/*.podspec'
    - '**/*.jbuilder'
    - '**/*.rabl'
    - '**/*.rake'
    - '**/*.opal'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Guardfile'
    - '**/Podfile'
    - '**/Thorfile'
    - '**/Vagrantfile'
    - '**/Berksfile'
    - '**/Cheffile'
    - '**/Vagabondfile'
    - '**/Fastfile'
    - '**/*Fastfile'
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/*'
    - 'slate/*'
    - 'client/*'
  TargetRubyVersion: 2.3
CaseIndentation:
  IndentOneStep: true
ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/IfUnlessModifier:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/Next:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
